from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    api_csrf_change_email,
    api_file_upload,
    api_login,
    api_reflected_xss,
    api_user_lookup,
    create_comment,
    csrf_get_token,
    csrf_secure_change_email,
    csrf_session_login,
    csrf_vulnerable_change_email,
    healthcheck,
    lab_mode,
    misconfig_cors_vuln,
    misconfig_cors_secure,
    misconfig_error_vuln,
    misconfig_error_secure,
    reflected_xss_secure,
    reflected_xss_vulnerable,
    register,
    secure_jwt_profile,
    secure_bruteforce_login,
    secure_file_upload,
    secure_login,
    secure_user_lookup,
    stored_xss_secure,
    stored_xss_vulnerable,
    vulnerable_jwt_profile,
    vulnerable_bruteforce_login,
    vulnerable_file_upload,
    vulnerable_idor_user_lookup,
    vulnerable_sqli_login,
)

urlpatterns = [
    path("health/", healthcheck, name="health"),
    path("lab/mode/", lab_mode, name="lab_mode"),
    path("auth/register/", register, name="register"),
    path(
        "auth/vuln/sqli-login/",
        vulnerable_sqli_login,
        name="vulnerable_sqli_login",
    ),
    path(
        "auth/secure/login/",
        secure_login,
        name="secure_login",
    ),
    path(
        "users/vuln/",
        vulnerable_idor_user_lookup,
        name="vulnerable_idor_user_lookup",
    ),
    path(
        "users/secure/",
        secure_user_lookup,
        name="secure_user_lookup",
    ),
    path("comments/", create_comment, name="create_comment"),
    path("xss/reflected/vuln/", reflected_xss_vulnerable, name="reflected_xss_vuln"),
    path("xss/reflected/secure/", reflected_xss_secure, name="reflected_xss_secure"),
    path("xss/stored/vuln/", stored_xss_vulnerable, name="stored_xss_vuln"),
    path("xss/stored/secure/", stored_xss_secure, name="stored_xss_secure"),
    path("auth/jwt/vuln/profile/", vulnerable_jwt_profile, name="vulnerable_jwt_profile"),
    path("auth/jwt/secure/profile/", secure_jwt_profile, name="secure_jwt_profile"),
    path("auth/bruteforce/vuln/login/", vulnerable_bruteforce_login, name="vulnerable_bruteforce_login"),
    path("auth/bruteforce/secure/login/", secure_bruteforce_login, name="secure_bruteforce_login"),
    path("upload/vuln/", vulnerable_file_upload, name="vulnerable_file_upload"),
    path("upload/secure/", secure_file_upload, name="secure_file_upload"),
    path("csrf/session-login/", csrf_session_login, name="csrf_session_login"),
    path("csrf/token/", csrf_get_token, name="csrf_get_token"),
    path("csrf/vuln/change-email/", csrf_vulnerable_change_email, name="csrf_vulnerable_change_email"),
    path("csrf/secure/change-email/", csrf_secure_change_email, name="csrf_secure_change_email"),
    path("misconfig/cors/vuln/", misconfig_cors_vuln, name="misconfig_cors_vuln"),
    path("misconfig/cors/secure/", misconfig_cors_secure, name="misconfig_cors_secure"),
    path("misconfig/error/vuln/", misconfig_error_vuln, name="misconfig_error_vuln"),
    path("misconfig/error/secure/", misconfig_error_secure, name="misconfig_error_secure"),
    path("auth/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    
    # Rotas Unificadas (Consumidas pelo Frontend)
    path("v1/login/", api_login, name="api_login_unified"),
    path("v1/users/", api_user_lookup, name="api_user_lookup_unified"),
    path("v1/upload/", api_file_upload, name="api_file_upload_unified"),
    path("v1/search/", api_reflected_xss, name="api_reflected_xss_unified"),
    path("v1/profile/email/", api_csrf_change_email, name="api_csrf_change_email_unified"),
]
