"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (if present)
load_dotenv(BASE_DIR / '.env')

# ---------------------------------------------------------------------------
# REAL-01 FIX: SECRET_KEY read from environment variable.
# Generate a new key with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# ---------------------------------------------------------------------------
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    # Fallback used ONLY when no .env file is present (e.g. CI without secrets).
    # Never rely on this in production.
    'django-insecure-fallback-key-override-via-env',
)

# ---------------------------------------------------------------------------
# REAL-02 FIX: DEBUG driven by environment variable (default: False).
# Set DJANGO_DEBUG=True in your .env for local development.
# ---------------------------------------------------------------------------
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ---------------------------------------------------------------------------
# REAL-03 FIX: ALLOWED_HOSTS driven by environment variable.
# Set DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1 in your .env.
# ---------------------------------------------------------------------------
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # REAL-04 FIX: django-cors-headers for proper CORS management.
    'corsheaders',
    'accounts',
]

MIDDLEWARE = [
    # REAL-04 FIX: CorsMiddleware must come BEFORE CommonMiddleware.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# REAL-04 FIX: CORS — allowed origins read from environment variable.
# By default only the Vite dev server is allowed. Override in production.
# The lab's intentional misconfiguration endpoints (misconfig/cors/vuln/)
# manually set their own headers — that behaviour is preserved.
# ---------------------------------------------------------------------------
_cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(',') if o.strip()]

# Allow cookies/auth headers in CORS requests from allowed origins only.
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# ---------------------------------------------------------------------------
# REAL-06 FIX: HTTP Security Headers.
# X-Frame-Options is already set to DENY by XFrameOptionsMiddleware (above).
# The settings below add additional protections.
# In production, also enable SECURE_HSTS_* and SECURE_SSL_REDIRECT.
# ---------------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True   # X-Content-Type-Options: nosniff
SECURE_BROWSER_XSS_FILTER = True     # Legacy X-XSS-Protection header
X_FRAME_OPTIONS = 'DENY'             # Reinforces the clickjacking middleware

# Production-only settings (enable when deploying behind HTTPS):
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
